export const ROUTES = {
  home: "/",
  login: "/login",
  signup: "/signup",
  forgotPassword: "/forgot-password",
  customer: {
    dashboard: "/customer/dashboard",
    vehicles: "/customer/vehicles",
    profile: "/customer/profile",
    appointments: "/customer/appointments",
    history: "/customer/history",
    partsRequest: "/customer/parts-request",
    reviews: "/customer/reviews",
  },
  staff: {
    dashboard: "/staff/dashboard",
    customerReports: "/staff/customer-reports",
    customers: "/staff/management",
    vehicles: "/staff/repair-orders",
    appointments: "/staff/inventory",
    partRequests: "/staff/vendor",
    sales: "/staff/invoices",
    reviews: "/staff/reviews",
    profile: "/staff/profile",
    settings: "/staff/settings",
    inventory: "/staff/inventory",
    repairOrders: "/staff/repair-orders",
    invoices: "/staff/invoices",
    management: "/staff/management",
    parts: "/staff/parts",
    vendor: "/staff/vendor",
  },
  admin: {
    dashboard: "/admin/dashboard",
    customerReports: "/admin/customer-reports",
    users: "/admin/users",
    vendors: "/admin/vendors",
    settings: "/admin/settings",
    analytics: "/admin/analytics",
    financialReports: "/admin/financial-reports",
    purchaseInvoices: "/admin/purchase-invoices",
    partRequests: "/admin/part-requests",
    reviews: "/admin/reviews",
  },
} as const;
